name QA Code Challenge
on [push, pull_request]
jobs
  Code-Challenge
    runs-on ubuntu-latest
    steps
      - name GetRepo
        uses actionscheckout@v3
      - name InstallCypressNodeandRun
        uses cypress-iogithub-action@v4
        with
          command npm run FullRegression